/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "i2c_lcd.h"
#include"accel.h"

int main(void)
{
	int ret;
	char str[64];
	SystemInit();
	LIS_Init();
	ret = Lcd_Init();
	LIS_Data val ;
	if(ret)
	{
		val = LIS_GetData();
	    sprintf(str ,"  x=%d, y=%d",val.x,val.y);
	    Lcd_Puts(LCD_LINE1, str);
	    sprintf(str ,"  z=%d",val.z);
	    Lcd_Puts(LCD_LINE2, str);
	}
	return 0;
}
