/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "intr_assign1.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	SwitchInit();
	LedInit(LED_GREEN_PIN);
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	int count = 1 ;
	while(1)
	{
	   if(SwitchExtiFlag == 1)
		  {
            if (count == 1)
           {
        	LedOn(LED_GREEN_PIN);
        	DelayMs(1000);
        	LedOff(LED_GREEN_PIN);
        	count++ ;
           }
         else if (count == 2)
                {
                	LedOn(LED_ORANGE_PIN);
                	DelayMs(1000);
                	LedOff(LED_ORANGE_PIN);
                	count++;
                }
        else if (count == 3)
                        {
                        	LedOn(LED_RED_PIN);
                        	DelayMs(1000);
                        	LedOff(LED_RED_PIN);
                        	count++ ;
                        }
            else
                         {
                        	LedOn(LED_BLUE_PIN);
                        	DelayMs(1000);
                        	LedOff(LED_BLUE_PIN);
                        	count = 1;
                           }
            SwitchExtiFlag = 0;
	}
	}
	return 0;
}























